#remote_theme: pmarsceill/just-the-docs
# OR
# remote_theme: rundocs/jekyll-rtd-theme
# OR
# remote_theme: carlosperate/jekyll-theme-rtd
# OR
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: MQSS Interfaces
description: Documentation for Munich Quantum Software Stack interfaces

markdown: kramdown
